[pytest]
testpaths = test
python_files = *_test.py test_*.py
python_classes = *Test*
python_functions = *test*
markers =
 api: marks tests as API tests (select with '-m "api"')
 ui: marks tests as user interface tests (select with '-m "ui"')